#!/usr/bin/env python3
"""PreToolUse brain - deterministic backstop for the human checkpoints.

Wired to Claude Code's `PreToolUse` event (matchers: Bash, Edit|Write). It denies
(exit code 2, reason on stderr) when:
  - `git commit` runs while the current task's commit is not yet approved;
  - `git push` runs while push is not approved, or targets the protected branch;
  - a code file is edited while the active task sits in the read-only `review`
    stage (bookkeeping under .claude/ and docs/ is always allowed);
  - a code file is edited while handoff debt exists and no task is mid-stage
    (config flag handoff.hard_edit_gate - see tools/pipeline/handoff.py);
  - the ORCHESTRATOR (main thread) writes outside its bookkeeping allowlist
    (.claude/, docs/, README*, root CLAUDE.md) - config block
    pipeline.json "orchestrator_gate". The orchestrator formalizes, delegates,
    verifies and synthesizes; it never authors code. Subagents are exempt
    (their own frontmatter hooks run agent_gate.py profiles instead): when the
    hook payload carries an agent identity, the orchestrator checks are skipped.

Everything else is allowed (exit 0). Fail-open: any error allows the tool, so a
bug here can never brick the agent.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import state

TASK_PREFIX = "task-"

# Branch-naming gate: a newly created work branch must follow
# <work-type>/...task-<id>... per .claude/rules/git-workflow.md, so agents stop
# cutting branches without a task number.
BRANCH_TYPES = ("feature", "bugfix", "hotfix", "enhancement", "techdebt",
                "fix", "refactor", "chore")
NEW_BRANCH_RE = re.compile(
    r"git\s+(?:checkout\s+-[bB]|switch\s+-[cC]|branch)\s+"
    r"(\"[^\"]+\"|'[^']+'|[^\s;&|]+)")
PROTECTED_BRANCHES = ("main", "staging", "production", "master", "develop")

# --- Generic gates (no project/stack scope - safe in the universal template) ---
# D: AI-authorship trailers forbidden in commit messages.
AI_ATTRIB_RE = re.compile(r"co-authored-by|generated by|generated with|ai-assisted|\U0001F916", re.IGNORECASE)
# F: em dash / en dash are forbidden anywhere. Referenced by escape so this
# source file itself stays free of the literal characters it bans.
EM_EN_DASH = (chr(0x2014), chr(0x2013))  # em dash, en dash

# --- Stack/project-specific gates are DATA, read from pipeline.json "gates" ---
# so the code stays language-agnostic and the template ships with empty defaults.
# Keys (all optional):
#   forbid_dev_null: bool          - block Unix /dev/null redirects (Windows)   [B]
#   destructive_command_patterns: [regex,...] - deny these commands              [A]
#   destructive_allow_if: [substr,...]        - ... unless one of these appears
#   repl_write_keyword: str        - REPL command name (e.g. a live shell)       [G]
#   repl_write_patterns: [regex,...] - write ops denied inside that REPL
def gates_cfg() -> dict:
    cfg = state.load_pipeline().get("gates", {})
    return cfg if isinstance(cfg, dict) else {}


# --- Shared redirect detection (used here and by agent_gate.py) ---
# A file-writing redirect (mutation) vs a read-only-safe descriptor dup / discard.
# `> file` and `2>> log` write files; `2>&1`, `>&2` only dup descriptors; `NUL`,
# `nul`, `/dev/null` discard. Only the first kind is a mutation. The lookbehind
# `(?<![-\w<>])` skips arrows like `->` / `-->` and glued word chars.
REDIR_RE = re.compile(r"(?<![-\w<>])\d*>>?\s*(?P<t>&\d+|[^\s;|&<>]+)")
DISCARD_TARGETS = ("nul", "/dev/null")


def redirect_write_target(command: str) -> str:
    """Return the file-writing redirect fragment, or '' if the command only dups
    descriptors (2>&1) or discards output (NUL / /dev/null)."""
    for m in REDIR_RE.finditer(command):
        target = m.group("t")
        if target.startswith("&"):
            continue  # descriptor dup, e.g. 2>&1 - not a file write
        if target.lower() in DISCARD_TARGETS:
            continue  # discard sink - not a tree mutation
        return m.group(0).strip()
    return ""


# --- Orchestrator gate (config: pipeline.json "orchestrator_gate") ---
# The main thread coordinates; it never authors code. Writes are allowed only
# under the bookkeeping allowlist. Subagent tool calls skip this (they carry an
# agent identity in the hook payload and are governed by agent_gate.py).
README_RE = re.compile(r"(^|[\\/])readme[^\\/]*(\.md)?$", re.IGNORECASE)
ORCH_SED_RE = re.compile(r"\bsed\s+(-\w*\s+)*-i", re.IGNORECASE)
ORCH_TEE_RE = re.compile(r"\btee\s+(?:-\w+\s+)*(?P<t>[^\s;|&]+)", re.IGNORECASE)
ORCH_PATCH_RE = re.compile(r"(^|[\s;|&])(patch\b|git\s+apply\b)", re.IGNORECASE)


def orch_cfg() -> dict:
    cfg = state.load_pipeline().get("orchestrator_gate", {})
    return cfg if isinstance(cfg, dict) else {}


def orch_enabled() -> bool:
    return bool(orch_cfg().get("enabled"))


def orch_allowed_path(file_path: str) -> bool:
    """Bookkeeping allowlist for the orchestrator: any .claude/ tree, docs/,
    README*, the root CLAUDE.md, the harness plan scratch (~/.claude/plans/),
    plus configurable extra_allow globs (matched repo-relative)."""
    try:
        raw = file_path.replace("\\", "/")
        low = raw.lower()
        if "/.claude/" in low or low.startswith(".claude/"):
            return True
        if "/docs/" in low or low.startswith("docs/"):
            return True
        if README_RE.search(low):
            return True
        p = Path(file_path)
        if not p.is_absolute():
            p = state.ROOT / p
        try:
            rel = p.resolve().relative_to(state.ROOT.resolve()).as_posix()
        except ValueError:
            # outside the project root: only the harness plan area is legal
            # (under_home_claude() already handled the rest of ~/.claude/)
            home_plans = (Path.home() / ".claude" / "plans").resolve()
            rp = p.resolve()
            return rp == home_plans or home_plans in rp.parents
        if rel.lower() in ("claude.md",):
            return True
        import fnmatch
        for pattern in orch_cfg().get("extra_allow", []):
            if fnmatch.fnmatch(rel, str(pattern)) or fnmatch.fnmatch(rel.lower(), str(pattern).lower()):
                return True
        return False
    except (OSError, ValueError):
        return True  # fail-open


def orch_check_edit(file_path: str) -> int:
    if not orch_enabled():
        return allow()
    if orch_allowed_path(file_path):
        return allow()
    return deny(f"Orchestrator never writes code: '{file_path}' is outside the bookkeeping "
                f"allowlist (.claude/, docs/, README*, root CLAUDE.md). Dispatch the owning "
                f"agent via the Agent tool instead. (orchestrator_gate - see "
                f".claude/rules/orchestration.md)")


def orch_check_bash(command: str) -> int:
    """Deny shell-based file authoring by the orchestrator: redirects and tee
    into non-allowlisted paths, in-place editors, patch application. Pipeline
    tooling, read-only git and the approval-gated commit/push flow stay intact."""
    if not orch_enabled():
        return allow()
    frag = redirect_write_target(command)
    if frag:
        target = frag.split(">")[-1].strip()
        if target and not orch_allowed_path(target):
            return deny(f"Orchestrator never writes files via shell redirects ('{frag}'). "
                        f"Dispatch the owning agent instead. (orchestrator_gate)")
    m = ORCH_TEE_RE.search(command)
    if m and not orch_allowed_path(m.group("t")):
        return deny(f"Orchestrator never writes files via tee ('{m.group(0)}'). "
                    f"Dispatch the owning agent instead. (orchestrator_gate)")
    if ORCH_SED_RE.search(command):
        return deny("Orchestrator never edits files in place (sed -i). Use Edit for "
                    "bookkeeping files or dispatch the owning agent. (orchestrator_gate)")
    if ORCH_PATCH_RE.search(command):
        return deny("Orchestrator never applies patches (patch / git apply). Dispatch "
                    "the owning agent instead. (orchestrator_gate)")
    return allow()

# Multi-repo workspaces: the workspace root is often NOT a git repo (the repos
# are subdirectories like backend/ and frontend/). The branch must be read from
# the repo the command actually targets, in priority order:
#   git -C <dir>  >  last `cd <dir>` in the command  >  session cwd  >  ROOT.
GIT_C_RE = re.compile(r"git\s+-C\s+(\"[^\"]+\"|'[^']+'|[^\s;&|]+)")
CD_RE = re.compile(r"(?:^|&&|\|\||;)\s*cd\s+(\"[^\"]+\"|'[^']+'|[^\s;&|]+)")


def deny(reason: str) -> int:
    sys.stderr.write(reason + "\n")
    return 2


def allow() -> int:
    return 0


def _unquote(s: str) -> str:
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        return s[1:-1]
    return s


def repo_candidates(command: str, cwd: str) -> list:
    """Directories to try for the branch check, most specific first."""
    base = Path(cwd) if cwd else state.ROOT
    dirs = []
    m = GIT_C_RE.search(command)
    if m:
        dirs.append(_unquote(m.group(1)))
    git_at = command.find("git ")
    cds = CD_RE.findall(command if git_at < 0 else command[:git_at])
    if cds:
        dirs.append(_unquote(cds[-1]))
    resolved = []
    for d in dirs:
        try:
            p = Path(d)
            resolved.append(p if p.is_absolute() else base / p)
        except (OSError, ValueError):
            pass
    resolved.append(base)
    if state.ROOT not in resolved:
        resolved.append(state.ROOT)
    return resolved


def current_branch(command: str = "", cwd: str = "") -> str:
    for repo in repo_candidates(command, cwd):
        try:
            if not Path(repo).is_dir():
                continue
            proc = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                cwd=str(repo), capture_output=True, text=True, timeout=10,
            )
            if proc.returncode == 0 and proc.stdout.strip():
                return proc.stdout.strip()
        except (OSError, subprocess.SubprocessError, ValueError):
            continue
    return ""


def task_from_branch(branch: str) -> str:
    # feature/task-0007 -> task-0007
    for part in branch.replace("\\", "/").split("/"):
        if part.startswith(TASK_PREFIX):
            return part
    if TASK_PREFIX in branch:
        idx = branch.index(TASK_PREFIX)
        return branch[idx:].split("/")[0]
    return ""


def valid_work_branch(name: str) -> bool:
    """A work branch must be <type>/...task-<id>... ; protected branches pass
    (checkout/switch to them is not new work)."""
    name = name.replace("\\", "/").strip()
    if name in PROTECTED_BRANCHES:
        return True
    if "/" not in name:
        return False
    prefix = name.split("/", 1)[0]
    if prefix not in BRANCH_TYPES:
        return False
    return bool(re.search(r"task-[a-z0-9]", name, re.IGNORECASE))


def check_branch_creation(command: str, cwd: str = "") -> int:
    """Deny creation of a work branch that breaks the <type>/task-XXXX naming
    rule [gate 4] or is cut from a base other than main [gate C]. Only fires on
    branch-creation forms; fail-open otherwise."""
    m = NEW_BRANCH_RE.search(command)
    if not m:
        return allow()
    name = _unquote(m.group(1))
    if not name or name.startswith("-"):  # flag, not a branch name (e.g. git branch -d)
        return allow()
    if name.replace("\\", "/") in PROTECTED_BRANCHES:
        return allow()
    if not valid_work_branch(name):
        return deny(
            f"Branch '{name}' breaks the naming rule. Use <type>/task-<id> "
            f"(types: {', '.join(BRANCH_TYPES)}), e.g. 'feature/task-0007' or "
            f"'bugfix/task-rbac-0012'. The task number is mandatory - see "
            f".claude/rules/git-workflow.md.")
    pipeline = state.load_pipeline()
    main_branch = str(pipeline.get("main_branch", "main"))
    if main_branch.startswith("{{"):
        main_branch = "main"
    return check_branch_base(command, cwd, name, main_branch)


def check_branch_base(command: str, cwd: str, name: str, main_branch: str) -> int:
    """C: a work branch must be cut from up-to-date main. Verify the base is
    main (explicit start-point on the command, else the current branch).
    Fail-open when git is unavailable."""
    after = command.split(name, 1)[1] if name in command else ""
    # Truncate at the first shell separator - anything past it is a new command
    # (e.g. `&& echo ...`), not the branch's start-point.
    for sep in ("&&", "||", ";", "|", "&", ">", "<", "\n"):
        idx = after.find(sep)
        if idx != -1:
            after = after[:idx]
    start_point = None
    for tok in after.split():
        tok = _unquote(tok)
        if tok and not tok.startswith("-"):
            start_point = tok
            break
    if start_point is not None:
        ok = start_point == main_branch or start_point.split("/")[-1] == main_branch
    else:
        cur = current_branch(command, cwd)
        ok = (cur == main_branch) or (cur == "")  # unknown branch -> fail-open
    if ok:
        return allow()
    return deny(
        f"Branch '{name}' must be cut from up-to-date '{main_branch}', not from the "
        f"current branch. Run: git checkout {main_branch} && git pull, then create the "
        f"branch. (branch-base-must-be-main - see .claude/rules/git-workflow.md).")


def check_destructive_and_repl(command: str, low: str) -> int:
    """A + B + G, all data-driven from pipeline.json 'gates' so no project/stack
    scope leaks into the code."""
    cfg = gates_cfg()

    if cfg.get("forbid_dev_null") and "/dev/null" in command:  # B
        return deny("Unix redirect to /dev/null is forbidden in this environment - it "
                    "creates a literal `nul` file. Drop the redirect or use `>NUL` / `2>NUL`.")

    allow_if = [str(s).lower() for s in cfg.get("destructive_allow_if", [])]  # A
    for pat in cfg.get("destructive_command_patterns", []):
        try:
            if re.search(pat, command, re.IGNORECASE):
                if any(a in low for a in allow_if):
                    return allow()
                return deny(f"Destructive command blocked by project policy (matched '{pat}'): "
                            f"it can irreversibly wipe data. Use the safe, additive alternative "
                            f"for this stack. See .claude project rules.")
        except re.error:
            continue

    kw = str(cfg.get("repl_write_keyword", "")).lower()  # G
    if kw and kw in low:
        for pat in cfg.get("repl_write_patterns", []):
            try:
                if re.search(pat, command, re.IGNORECASE):
                    return deny("Write operation inside the live REPL hits the real dev "
                                "database and persists junk. Use a rolled-back test or "
                                "read-only queries instead. See .claude testing rules.")
            except re.error:
                continue
    return allow()


def check_commit_attribution(command: str, low: str) -> int:
    """D: no AI-authorship trailer in commit messages."""
    if "git commit" not in low:
        return allow()
    if AI_ATTRIB_RE.search(command):
        return deny("Commit message carries an AI-authorship trailer (Co-Authored-By / "
                    "Generated by / AI-assisted). Remove it - no AI attribution in commits, ever.")
    return allow()


def has_forbidden_dash(text: str) -> bool:
    return any(d in text for d in EM_EN_DASH)


def under_home_claude(file_path: str) -> bool:
    """H: writes under the runtime home ~/.claude/ (never the project's own
    .claude/) store project data outside the repo - forbidden. Exception:
    ~/.claude/plans/ is the harness's own plan-mode scratch area (Claude Code
    forces the plan file there); denying it bricks plan mode, and the final
    plan is copied into <project>/.claude/plans/ anyway."""
    try:
        p = Path(file_path).resolve()
        home_claude = (Path.home() / ".claude").resolve()
        if p == home_claude or home_claude in p.parents:
            if (home_claude / "plans") in p.parents:
                return False  # harness plan-mode scratch file - allowed
            # allow if it is actually the project's own .claude (repo under home)
            root_claude = (state.ROOT / ".claude").resolve()
            return not (p == root_claude or root_claude in p.parents)
        return False
    except (OSError, ValueError):
        return False


def active_review_run(conn) -> dict | None:
    """Read-only stages freeze code edits: 'review' (reviewer analyzes the tree)
    and 'diff-review' (the CEO reviews the diff - edits would invalidate it)."""
    for r in state.all_runs(conn):
        if r["stage"] in ("review", "diff-review") and r["stage_status"] != state.ST_BLOCKED:
            return r
    return None


def is_bookkeeping(path: str) -> bool:
    p = path.replace("\\", "/").lower()
    return "/.claude/" in p or p.startswith(".claude/") or "/docs/" in p or p.startswith("docs/")


def handoff_freeze_task() -> str:
    """Hard edit gate (config flag handoff.hard_edit_gate): while a completed
    task lacks its handoff doc AND no task is mid-stage, code edits are frozen -
    the debt must be paid first. A task already in an editing stage keeps
    working (it registered before the debt appeared). Lazy import + fail-open:
    '' means no freeze."""
    try:
        import handoff
        if not handoff.cfg().get("hard_edit_gate"):
            return ""
        conn = state.connect()
        try:
            editing = any(r["stage"] in state.EDITING_STAGES
                          and r["stage_status"] != state.ST_BLOCKED
                          for r in state.all_runs(conn))
        finally:
            conn.close()
        if editing:
            return ""
        debt = handoff.uncovered_done_tasks()
        return debt[0]["task"] if debt else ""
    except Exception:
        return ""


def handle_bash(command: str, cwd: str = "", orch: bool = False) -> int:
    low = " ".join(command.lower().split())

    for check in (
        check_branch_creation(command, cwd),      # 4 (naming) + C (base)
        check_destructive_and_repl(command, low),  # A + B + G
        check_commit_attribution(command, low),    # D
        orch_check_bash(command) if orch else allow(),  # orchestrator profile
    ):
        if check != 0:
            return check

    is_commit = "git commit" in low
    is_push = "git push" in low
    if not (is_commit or is_push):
        return allow()

    pipeline = state.load_pipeline()
    main_branch = str(pipeline.get("main_branch", "main"))
    if main_branch.startswith("{{"):
        main_branch = "main"
    branch = current_branch(command, cwd)

    if is_push and (branch == main_branch or " origin main" in low or low.endswith(" main")):
        return deny(f"Push to protected branch '{main_branch}' is forbidden. "
                    "Push the feature branch; the CEO merges via PR.")

    task = task_from_branch(branch)
    if not task:
        if is_commit:
            return deny("Not on a feature branch (no task-XXXX). Create the task branch first "
                        "per .claude/rules/git-workflow.md.")
        return allow()

    conn = state.connect()
    run = state.get_run(conn, task)
    conn.close()
    if run is None:
        return allow()  # task not under pipeline control - don't interfere

    if is_commit and not run["commit_approved"]:
        return deny(f"Commit for {task} is not approved yet. Surface the diff and wait for CEO "
                    f"approval, then: python .claude/tools/pipeline/approve.py --task {task} --gate commit.")
    if is_push and not run["push_approved"]:
        return deny(f"Push for {task} is not approved yet. Wait for CEO approval, then: "
                    f"python .claude/tools/pipeline/approve.py --task {task} --gate push.")
    return allow()


def handle_edit(file_path: str, content: str = "", orch: bool = False) -> int:
    if not file_path:
        return allow()

    if under_home_claude(file_path):  # H
        return deny("Project files must not be written under the runtime home ~/.claude/. "
                    "Keep everything inside the project (its own .claude/, docs/, src, ...).")

    if content and has_forbidden_dash(content):  # F
        return deny("Content contains an em dash or en dash (U+2014 / U+2013). Use a plain "
                    "hyphen '-' everywhere - code, comments, docs, strings. (global rule)")

    if orch:
        code = orch_check_edit(file_path)
        if code != 0:
            return code

    if is_bookkeeping(file_path):
        return allow()
    conn = state.connect()
    review = active_review_run(conn)
    conn.close()
    if review:
        return deny(f"{review['task']} is in the read-only '{review['stage']}' stage - code edits "
                    f"are blocked. To change code, send it back: python "
                    f".claude/tools/pipeline/approve.py --task {review['task']} --reject "
                    f"(diff-review: the CEO's 'Request changes' verdict does this automatically).")
    frozen = handoff_freeze_task()
    if frozen:
        return deny(f"Handoff debt: completed task {frozen} has no valid handoff doc - code edits "
                    f"are frozen (handoff.hard_edit_gate) until the next task's assignee writes it. "
                    f"Scaffold: python .claude/tools/pipeline/handoff.py --for {frozen}, then fill "
                    f".claude/tasks/handoffs/{frozen}.md. Check: handoff.py --check.")
    return allow()


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (ValueError, OSError):
        return allow()
    try:
        tool = payload.get("tool_name", "")
        ti = payload.get("tool_input", {}) or {}
        # Subagent detection: settings-level hooks also fire inside subagents,
        # but the orchestrator profile must only bind the MAIN thread (subagents
        # carry their own frontmatter hooks -> agent_gate.py). Two signals:
        #   1. explicit agent identity keys in the payload (newer harnesses);
        #   2. the transcript path - subagent transcripts live under a
        #      .../subagents/ directory as agent-<id>.jsonl.
        is_subagent = any(str(payload.get(k) or "").strip()
                          for k in ("agent_type", "subagent_type", "agent_name", "agent_id"))
        tp = str(payload.get("transcript_path") or "").replace("\\", "/").lower()
        if "/subagents/" in tp or tp.rsplit("/", 1)[-1].startswith("agent-"):
            is_subagent = True
        orch = not is_subagent
        if tool == "Bash":
            return handle_bash(str(ti.get("command", "")), str(payload.get("cwd", "")), orch=orch)
        if tool in ("Edit", "Write"):
            content = str(ti.get("new_string", "") or ti.get("content", ""))
            return handle_edit(str(ti.get("file_path", "")), content, orch=orch)
        return allow()
    except Exception:
        return allow()


if __name__ == "__main__":
    raise SystemExit(main())
