#!/usr/bin/env python3
"""PreToolUse brain - deterministic backstop for the human checkpoints.

Wired to Claude Code's `PreToolUse` event (matchers: Bash, Edit|Write). It denies
(exit code 2, reason on stderr) when:
  - `git commit` runs while the current task's commit is not yet approved;
  - `git push` runs while push is not approved, or targets ANY protected branch
    (main and master always, plus the configured trunk and pipeline.json
    "protected_branches" - default staging / production);
  - a code file is edited while the active task sits in the read-only `review`
    stage (bookkeeping under .claude/ and docs/ is always allowed);
  - a code file is edited while handoff debt exists and no task is mid-stage
    (config flag handoff.hard_edit_gate - see tools/pipeline/handoff.py);
  - the ORCHESTRATOR (main thread) writes outside its bookkeeping allowlist
    (.claude/, docs/, README*, root CLAUDE.md) - config block
    pipeline.json "orchestrator_gate". The orchestrator formalizes, delegates,
    verifies and synthesizes; it never authors code. Subagents are exempt
    (their own frontmatter hooks run agent_gate.py profiles instead): when the
    hook payload carries an agent identity, the orchestrator checks are skipped.

Everything else is allowed (exit 0). Fail-open: any error allows the tool, so a
bug here can never brick the agent.
"""

from __future__ import annotations

import json
import re
import shlex
import subprocess
import sys
from pathlib import Path

import state

TASK_PREFIX = "task-"

# Branch-naming gate: a newly created work branch must follow
# <work-type>/...task-<id>... per .claude/rules/git-workflow.md, so agents stop
# cutting branches without a task number.
BRANCH_TYPES = ("feature", "bugfix", "hotfix", "enhancement", "techdebt",
                "fix", "refactor", "chore")
PROTECTED_BRANCHES = ("main", "staging", "production", "master", "develop")

# Push protection is a SET, not the single `main_branch` name. Two names are
# protected unconditionally: `main` and `master` are never a work branch in any
# project, so there is no legitimate push to weigh against - and a template that
# only reads `main_branch` ships with ZERO protection for a `master` project
# until someone remembers to set the key, failing silently. The configured trunk
# and the optional pipeline.json "protected_branches" list join them, so extra
# environments need config, not code.
PUSH_PROTECTED_ALWAYS = ("main", "master")
PUSH_PROTECTED_DEFAULT = ("staging", "production")

# `git push` options that consume the NEXT argv entry (the `--opt=value`
# spelling is one token and falls through the generic flag skip).
PUSH_OPTS_WITH_ARG = frozenset({"--repo", "-o", "--push-option",
                                "--receive-pack", "--exec"})

# --- Generic gates (no project/stack scope - safe in the universal template) ---
# D: AI-authorship trailers forbidden in commit messages.
AI_ATTRIB_RE = re.compile(r"co-authored-by|generated by|generated with|ai-assisted|\U0001F916", re.IGNORECASE)
# F: em dash / en dash are forbidden anywhere. Referenced by escape so this
# source file itself stays free of the literal characters it bans.
EM_EN_DASH = (chr(0x2014), chr(0x2013))  # em dash, en dash

# --- Stack/project-specific gates are DATA, read from pipeline.json "gates" ---
# so the code stays language-agnostic and the template ships with empty defaults.
# Keys (all optional):
#   forbid_dev_null: bool          - block Unix /dev/null redirects (Windows)   [B]
#   destructive_command_patterns: [regex,...] - deny these commands              [A]
#   destructive_allow_if: [substr,...]        - ... unless one of these appears
#   repl_write_keyword: str        - REPL command name (e.g. a live shell)       [G]
#   repl_write_patterns: [regex,...] - write ops denied inside that REPL
def gates_cfg() -> dict:
    cfg = state.load_pipeline().get("gates", {})
    return cfg if isinstance(cfg, dict) else {}


# --- Shared redirect detection (used here and by agent_gate.py) ---
# A file-writing redirect (mutation) vs a read-only-safe descriptor dup / discard.
# `> file` and `2>> log` write files; `2>&1`, `>&2` only dup descriptors; `NUL`,
# `nul`, `/dev/null` discard. Only the first kind is a mutation. The lookbehind
# `(?<![-\w<>])` skips arrows like `->` / `-->` and glued word chars.
REDIR_RE = re.compile(r"(?<![-\w<>])\d*>>?\s*(?P<t>&\d+|[^\s;|&<>]+)")
DISCARD_TARGETS = ("nul", "/dev/null")


def redirect_write_target(command: str) -> str:
    """Return the file-writing redirect fragment, or '' if the command only dups
    descriptors (2>&1) or discards output (NUL / /dev/null)."""
    for m in REDIR_RE.finditer(command):
        target = m.group("t")
        if target.startswith("&"):
            continue  # descriptor dup, e.g. 2>&1 - not a file write
        if target.lower() in DISCARD_TARGETS:
            continue  # discard sink - not a tree mutation
        return m.group(0).strip()
    return ""


# --- Orchestrator gate (config: pipeline.json "orchestrator_gate") ---
# The main thread coordinates; it never authors code. Writes are allowed only
# under the bookkeeping allowlist. Subagent tool calls skip this (they carry an
# agent identity in the hook payload and are governed by agent_gate.py).
README_RE = re.compile(r"(^|[\\/])readme[^\\/]*(\.md)?$", re.IGNORECASE)
ORCH_SED_RE = re.compile(r"\bsed\s+(-\w*\s+)*-i", re.IGNORECASE)
ORCH_TEE_RE = re.compile(r"\btee\s+(?:-\w+\s+)*(?P<t>[^\s;|&]+)", re.IGNORECASE)
ORCH_PATCH_RE = re.compile(r"(^|[\s;|&])(patch\b|git\s+apply\b)", re.IGNORECASE)


def orch_cfg() -> dict:
    cfg = state.load_pipeline().get("orchestrator_gate", {})
    return cfg if isinstance(cfg, dict) else {}


def orch_enabled() -> bool:
    return bool(orch_cfg().get("enabled"))


def orch_allowed_path(file_path: str) -> bool:
    """Bookkeeping allowlist for the orchestrator: any .claude/ tree, docs/,
    README*, the root CLAUDE.md, the harness plan scratch (~/.claude/plans/),
    plus configurable extra_allow globs (matched repo-relative)."""
    try:
        raw = file_path.replace("\\", "/")
        low = raw.lower()
        if "/.claude/" in low or low.startswith(".claude/"):
            return True
        if "/docs/" in low or low.startswith("docs/"):
            return True
        if README_RE.search(low):
            return True
        p = Path(file_path)
        if not p.is_absolute():
            p = state.ROOT / p
        try:
            rel = p.resolve().relative_to(state.ROOT.resolve()).as_posix()
        except ValueError:
            # outside the project root: only the harness plan area is legal
            # (under_home_claude() already handled the rest of ~/.claude/)
            home_plans = (Path.home() / ".claude" / "plans").resolve()
            rp = p.resolve()
            return rp == home_plans or home_plans in rp.parents
        if rel.lower() == "claude.md":
            return True
        import fnmatch
        for pattern in orch_cfg().get("extra_allow", []):
            if fnmatch.fnmatch(rel, str(pattern)) or fnmatch.fnmatch(rel.lower(), str(pattern).lower()):
                return True
        return False
    except (OSError, ValueError):
        return True  # fail-open


def orch_check_edit(file_path: str) -> int:
    if not orch_enabled():
        return allow()
    if orch_allowed_path(file_path):
        return allow()
    return deny(f"Orchestrator never writes code: '{file_path}' is outside the bookkeeping "
                f"allowlist (.claude/, docs/, README*, root CLAUDE.md). Dispatch the owning "
                f"agent via the Agent tool instead. (orchestrator_gate - see "
                f".claude/rules/orchestration.md)")


def orch_check_bash(command: str) -> int:
    """Deny shell-based file authoring by the orchestrator: redirects and tee
    into non-allowlisted paths, in-place editors, patch application. Pipeline
    tooling, read-only git and the approval-gated commit/push flow stay intact."""
    if not orch_enabled():
        return allow()
    frag = redirect_write_target(command)
    if frag:
        target = frag.split(">")[-1].strip()
        if target and not orch_allowed_path(target):
            return deny(f"Orchestrator never writes files via shell redirects ('{frag}'). "
                        f"Dispatch the owning agent instead. (orchestrator_gate)")
    m = ORCH_TEE_RE.search(command)
    if m and not orch_allowed_path(m.group("t")):
        return deny(f"Orchestrator never writes files via tee ('{m.group(0)}'). "
                    f"Dispatch the owning agent instead. (orchestrator_gate)")
    if ORCH_SED_RE.search(command):
        return deny("Orchestrator never edits files in place (sed -i). Use Edit for "
                    "bookkeeping files or dispatch the owning agent. (orchestrator_gate)")
    if ORCH_PATCH_RE.search(command):
        return deny("Orchestrator never applies patches (patch / git apply). Dispatch "
                    "the owning agent instead. (orchestrator_gate)")
    return allow()

# Multi-repo workspaces: the workspace root is often NOT a git repo (the repos
# are subdirectories like backend/ and frontend/). The branch must be read from
# the repo the command actually targets, in priority order:
#   git -C <dir>  >  last `cd <dir>` in the command  >  session cwd  >  ROOT.
GIT_C_RE = re.compile(r"git\s+-C\s+(\"[^\"]+\"|'[^']+'|[^\s;&|]+)")
CD_RE = re.compile(r"(?:^|&&|\|\||;)\s*cd\s+(\"[^\"]+\"|'[^']+'|[^\s;&|]+)")


def deny(reason: str) -> int:
    sys.stderr.write(reason + "\n")
    return 2


def allow() -> int:
    return 0


def _unquote(s: str) -> str:
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        return s[1:-1]
    return s


# --- Git argv resolution: the single source of truth for "which subcommand?" ---
# Substring matching (`"git commit" in command`) is defeated by ANY global option
# sitting between `git` and its subcommand - `git -C dir push origin main`,
# `git -c user.name=x commit -m y`, `git --no-pager commit`. Every gate that
# identified a subcommand that way could be bypassed with one extra flag, so
# subcommand resolution now happens here, once, by walking argv.
GIT_UNKNOWN = "?"  # git text that could not be parsed - callers MUST gate it

# Global options that consume the NEXT argv entry. The `--opt=value` spelling
# needs no entry: it is a single token and falls through the generic flag skip.
GIT_OPTS_WITH_ARG = frozenset({
    "-C", "-c", "--git-dir", "--work-tree", "--namespace", "--exec-path",
    "--super-prefix", "--config-env", "--attr-source",
})
GIT_TOKEN_RE = re.compile(r"^(?:.*[\\/])?git(?:\.exe)?$", re.IGNORECASE)
MENTIONS_GIT_RE = re.compile(r"(?<![\w.-])git(?:\.exe)?(?![\w.-])", re.IGNORECASE)
# A token that ends the current command: shell separator or redirect.
SEGMENT_BREAK_RE = re.compile(r"^(?:&&|\|\||;|\||&|\d*[<>])")

# Separators a shell splits on even with no surrounding whitespace. shlex does
# NOT split on them, so `git status&&git add -A` tokenises as one glued token
# ('status&&git'), the second `git` is never seen, and every argv-based gate goes
# blind. Longest first so `&&` / `||` win over `&` / `|`.
SHELL_SEPARATORS = ("&&", "||", ";", "|", "&")


def pad_separators(command: str) -> str:
    """Insert whitespace around glued shell separators, outside quotes.

    `git status&&git add -A` -> `git status && git add -A`, so shlex yields the
    second `git` as its own token. Quoted regions are copied verbatim: padding
    inside them would rewrite a commit message or a branch name."""
    out = []
    quote = ""
    i = 0
    while i < len(command):
        ch = command[i]
        if quote:
            out.append(ch)
            if ch == quote:
                quote = ""
            elif ch == "\\" and quote == '"' and i + 1 < len(command):
                out.append(command[i + 1])
                i += 1
            i += 1
            continue
        if ch in "\"'":
            quote = ch
            out.append(ch)
            i += 1
            continue
        sep = next((s for s in SHELL_SEPARATORS if command.startswith(s, i)), "")
        if sep:
            out.append(" " + sep + " ")
            i += len(sep)
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def git_invocations(command: str) -> list:
    """[(subcommand, args), ...] - one entry per `git` call in `command`.

    Global options are skipped, and the ones taking a separate argument consume
    it, so `git -C dir push origin main` resolves to ('push', ['origin', 'main']).
    `args` stops at the first shell separator, redirect, or next `git` token, so
    `&&` / `;` chains yield one entry per link.

    Glued separators are normalised first (pad_separators), so
    `git status&&git add -A` resolves to [('status', []), ('add', ['-A'])]
    instead of hiding the second call inside one token.

    The failure mode is deliberately fail-CLOSED: when the text mentions git but
    shlex cannot tokenise it, the subcommand is GIT_UNKNOWN and callers must
    treat it as needing the gate. For these checks, failing open reopens the
    bypass. A git call carrying no subcommand at all (`git --version`) yields
    no entry - that is resolved, not unknown.
    """
    if not MENTIONS_GIT_RE.search(command):
        return []
    try:
        tokens = shlex.split(pad_separators(command), posix=True)
    except ValueError:
        return [(GIT_UNKNOWN, [])]
    found = []
    i = 0
    while i < len(tokens):
        if not GIT_TOKEN_RE.match(tokens[i]):
            i += 1
            continue
        j, sub = i + 1, ""
        while j < len(tokens):
            tok = tokens[j]
            if SEGMENT_BREAK_RE.match(tok):
                break
            if tok.startswith("-"):
                j += 2 if tok in GIT_OPTS_WITH_ARG else 1
                continue
            sub = tok.lower()
            j += 1
            break
        if sub:
            args = []
            while (j < len(tokens) and not SEGMENT_BREAK_RE.match(tokens[j])
                   and not GIT_TOKEN_RE.match(tokens[j])):
                args.append(tokens[j])
                j += 1
            found.append((sub, args))
        i = max(j, i + 1)
    return found


UNPARSEABLE_GIT_MSG = (
    "This command mentions git but cannot be tokenised (unbalanced quote - often an "
    "apostrophe in a message or heredoc body). The gate cannot tell which git "
    "subcommand would run, so it refuses rather than guessing. Rewrite the command "
    "with balanced quotes (or write the text with Write/Edit instead of a heredoc).")


def git_unparseable(command: str) -> bool:
    """True when the text mentions git but shlex could not tokenise it."""
    return any(sub == GIT_UNKNOWN for sub, _ in git_invocations(command))


def git_invokes(command: str, *subcommands: str) -> bool:
    """True when `command` runs one of `subcommands` ('commit', 'push', ...).

    Unparseable git text counts as a match (fail-closed), and a plain substring
    match is kept as a safety net for forms argv walking cannot see from the
    outside, such as `bash -c "git push origin main"`."""
    for sub, _ in git_invocations(command):
        if sub == GIT_UNKNOWN or sub in subcommands:
            return True
    low = " ".join(command.lower().split())
    return any(f"git {s}" in low for s in subcommands)


def repo_candidates(command: str, cwd: str) -> list:
    """Directories to try for the branch check, most specific first."""
    base = Path(cwd) if cwd else state.ROOT
    dirs = []
    m = GIT_C_RE.search(command)
    if m:
        dirs.append(_unquote(m.group(1)))
    git_at = command.find("git ")
    cds = CD_RE.findall(command if git_at < 0 else command[:git_at])
    if cds:
        dirs.append(_unquote(cds[-1]))
    resolved = []
    for d in dirs:
        try:
            p = Path(d)
            resolved.append(p if p.is_absolute() else base / p)
        except (OSError, ValueError):
            pass
    resolved.append(base)
    if state.ROOT not in resolved:
        resolved.append(state.ROOT)
    return resolved


def current_branch(command: str = "", cwd: str = "") -> str:
    for repo in repo_candidates(command, cwd):
        try:
            if not Path(repo).is_dir():
                continue
            proc = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                cwd=str(repo), capture_output=True, text=True, timeout=10,
            )
            if proc.returncode == 0 and proc.stdout.strip():
                return proc.stdout.strip()
        except (OSError, subprocess.SubprocessError, ValueError):
            continue
    return ""


def task_from_branch(branch: str) -> str:
    # feature/task-0007 -> task-0007
    for part in branch.replace("\\", "/").split("/"):
        if part.startswith(TASK_PREFIX):
            return part
    if TASK_PREFIX in branch:
        idx = branch.index(TASK_PREFIX)
        return branch[idx:].split("/")[0]
    return ""


def valid_work_branch(name: str) -> bool:
    """A work branch must be <type>/...task-<id>... ; protected branches pass
    (checkout/switch to them is not new work)."""
    name = name.replace("\\", "/").strip()
    if name in PROTECTED_BRANCHES:
        return True
    if "/" not in name:
        return False
    prefix = name.split("/", 1)[0]
    if prefix not in BRANCH_TYPES:
        return False
    return bool(re.search(r"task-[a-z0-9]", name, re.IGNORECASE))


BRANCH_CREATE_FLAGS = {"checkout": ("-b", "-B"), "switch": ("-c", "-C")}


def new_branch_name(command: str) -> tuple:
    """(name, trailing_args) for a branch-CREATION command, else ('', []).

    Forms: `git checkout -b NAME [start-point]`, `git switch -c NAME [start-point]`,
    `git branch NAME [start-point]`. Resolved through git_invocations(), so a
    global option no longer hides the subcommand (`git -C dir checkout -b x`).

    Unparseable git text returns (GIT_UNKNOWN, []) - this used to return ('', [])
    and thereby ALLOW, the one caller that read the sentinel as "not a git
    command". The caller must gate it (see check_branch_creation)."""
    for sub, args in git_invocations(command):
        if sub == GIT_UNKNOWN:
            return GIT_UNKNOWN, []
        if sub == "branch":
            if args and not args[0].startswith("-"):
                return args[0], args[1:]
        elif sub in BRANCH_CREATE_FLAGS:
            for n, tok in enumerate(args):
                if tok == "--":
                    break
                if tok in BRANCH_CREATE_FLAGS[sub]:
                    rest = args[n + 1:]
                    if rest and not rest[0].startswith("-"):
                        return rest[0], rest[1:]
                    break
    return "", []


def check_branch_creation(command: str, cwd: str = "") -> int:
    """Deny creation of a work branch that breaks the <type>/task-XXXX naming
    rule [gate 4] or is cut from a base other than main [gate C]. Only fires on
    branch-creation forms; fail-open otherwise. Unparseable git text gates
    (GIT_UNKNOWN): the branch name cannot be read, so neither rule can be
    checked."""
    name, rest = new_branch_name(command)
    if name == GIT_UNKNOWN:
        return deny(UNPARSEABLE_GIT_MSG)
    if not name:
        return allow()
    if name.replace("\\", "/") in PROTECTED_BRANCHES:
        return allow()
    if not valid_work_branch(name):
        return deny(
            f"Branch '{name}' breaks the naming rule. Use <type>/task-<id> "
            f"(types: {', '.join(BRANCH_TYPES)}), e.g. 'feature/task-0007' or "
            f"'bugfix/task-rbac-0012'. The task number is mandatory - see "
            f".claude/rules/git-workflow.md.")
    pipeline = state.load_pipeline()
    main_branch = str(pipeline.get("main_branch", "main"))
    if main_branch.startswith("{{"):
        main_branch = "main"
    return check_branch_base(command, cwd, name, rest, main_branch)


def check_branch_base(command: str, cwd: str, name: str, rest: list, main_branch: str) -> int:
    """C: a work branch must be cut from up-to-date main. Verify the base is
    main (explicit start-point after the branch name, else the current branch).
    `rest` already stops at the first shell separator - anything past it is a
    new command (e.g. `&& echo ...`), not the branch's start-point.
    Fail-open when git is unavailable."""
    start_point = next((tok for tok in rest if tok and not tok.startswith("-")), None)
    if start_point is not None:
        ok = start_point == main_branch or start_point.split("/")[-1] == main_branch
    else:
        cur = current_branch(command, cwd)
        ok = (cur == main_branch) or (cur == "")  # unknown branch -> fail-open
    if ok:
        return allow()
    return deny(
        f"Branch '{name}' must be cut from up-to-date '{main_branch}', not from the "
        f"current branch. Run: git checkout {main_branch} && git pull, then create the "
        f"branch. (branch-base-must-be-main - see .claude/rules/git-workflow.md).")


def push_protected_branches() -> set:
    """Every branch a push may never target: main + master always, the
    configured trunk, and pipeline.json "protected_branches" (default staging /
    production). Unresolved `{{PLACEHOLDER}}` values are ignored."""
    pipeline = state.load_pipeline()
    names = set(PUSH_PROTECTED_ALWAYS)
    trunk = str(pipeline.get("main_branch") or "main")
    if not trunk.startswith("{{"):
        names.add(trunk)
    extra = pipeline.get("protected_branches")
    if not isinstance(extra, (list, tuple)):
        extra = PUSH_PROTECTED_DEFAULT
    for name in extra:
        name = str(name).strip()
        if name and not name.startswith("{{"):
            names.add(name)
    return names


def push_refspec_targets(args: list) -> list:
    """Destination branch names named by a `git push` argv.

    The first non-flag token is the remote; each remaining one is a refspec.
    `main`, `+main`, `HEAD:main`, `feature:main`, `:main` (delete) and
    `refs/heads/main` all resolve to 'main'. An empty result means the command
    named no refspec, so the caller falls back to the checked-out branch."""
    positional = []
    i = 0
    while i < len(args):
        tok = args[i]
        if tok == "--":
            positional.extend(a for a in args[i + 1:] if a)
            break
        if tok.startswith("-"):
            i += 2 if tok in PUSH_OPTS_WITH_ARG else 1
            continue
        positional.append(tok)
        i += 1
    targets = []
    for spec in positional[1:]:  # positional[0] is the remote
        dst = spec.lstrip("+").rsplit(":", 1)[-1]
        dst = re.sub(r"^refs/heads/", "", dst)
        if dst:
            targets.append(dst)
    return targets


def push_target_branches(command: str, branch: str) -> list | None:
    """Branch names the push would land on, or None when it cannot be resolved.

    Fail-CLOSED by design: None means the caller must DENY. Fail-open belongs at
    the top-level exception handler, not in the step that decides whether a push
    is gated - guessing "probably fine" there is exactly how a protected branch
    gets pushed. Returns None for a push visible only to the substring net
    (`bash -c "git push origin main"`), and for a refspec-less push whose
    checked-out branch could not be read."""
    invocations = [args for sub, args in git_invocations(command) if sub == "push"]
    if not invocations:
        return None
    targets = []
    for args in invocations:
        specs = push_refspec_targets(args)
        if specs:
            targets.extend(specs)
        elif branch:
            targets.append(branch)
        else:
            return None
    return targets


def check_push_target(command: str, branch: str) -> int:
    """Deny a push landing on any protected branch, in every spelling the argv
    resolver can see: `origin main`, `HEAD:main`, `+main`, `--force origin main`,
    `feature:main`, and the refspec-less form while sitting on a protected
    branch."""
    protected = push_protected_branches()
    targets = push_target_branches(command, branch)
    if targets is None:
        return deny(
            "This push cannot be resolved to a target branch, so the gate refuses "
            "rather than guessing (an unresolvable push gates). Run git push "
            "directly instead of wrapping it in another shell, and name the branch: "
            "git push -u origin <type>/task-<id>. The CEO merges via a PR.")
    for name in targets:
        if name in protected:
            return deny(
                f"Push to protected branch '{name}' is forbidden (protected: "
                f"{', '.join(sorted(protected))}). Push your work branch instead - "
                f"the CEO merges into '{name}' via a PR. See "
                f".claude/rules/git-workflow.md.")
    return allow()


def repo_bootstrap(command: str, cwd: str, main_branch: str) -> bool:
    """FR-1: true when the repo has no commits yet (unborn HEAD), or the
    configured main branch does not exist yet - there is no main to cut a
    task branch from, so the branch-naming/base rule cannot apply. Fail-open
    means "no exemption" here: any git error falls back to the existing,
    unchanged branch-gate behavior rather than silently granting a bypass."""
    for repo in repo_candidates(command, cwd):
        try:
            if not Path(repo).is_dir():
                continue
            # A non-zero exit from `rev-parse --verify HEAD` means EITHER
            # "unborn HEAD" OR "not a git repository at all" - the two are
            # indistinguishable from that command alone. Confirm this really
            # is a repo first; if not, fall through to the next candidate
            # (same fall-through discipline as current_branch/staged_files),
            # instead of granting a bootstrap exemption for a path that has
            # no repo here (e.g. the workspace root in a multi-repo layout).
            is_repo = subprocess.run(
                ["git", "rev-parse", "--is-inside-work-tree"],
                cwd=str(repo), capture_output=True, text=True, timeout=10,
            )
            if is_repo.returncode != 0 or is_repo.stdout.strip() != "true":
                continue
            head = subprocess.run(
                ["git", "rev-parse", "--verify", "-q", "HEAD"],
                cwd=str(repo), capture_output=True, text=True, timeout=10,
            )
            if head.returncode != 0:
                return True  # unborn HEAD - zero commits
            branch = subprocess.run(
                ["git", "rev-parse", "--verify", "-q", f"refs/heads/{main_branch}"],
                cwd=str(repo), capture_output=True, text=True, timeout=10,
            )
            return branch.returncode != 0
        except (OSError, subprocess.SubprocessError, ValueError):
            continue
    return False


# --- Contract C-2: planning-and-documentation path set (FR-21, FR-22) ---
# Both the pre-move .claude/ spelling and the post-FR-13 .agentry/ spelling
# are included so the exemption survives the move unchanged.
C2_PREFIXES = (
    ".agentry/plans/", ".claude/plans/",
    ".agentry/specs/", ".claude/specs/",
    ".agentry/tasks/", ".claude/tasks/",
    "docs/",
)
C2_ROOT_MD_RE = re.compile(r"^[^/]+\.md$", re.IGNORECASE)


def matches_c2(path: str) -> bool:
    p = path.replace("\\", "/").lower()
    if C2_ROOT_MD_RE.match(p):
        return True
    return any(p.startswith(prefix) for prefix in C2_PREFIXES)


def staged_files(command: str, cwd: str) -> list:
    for repo in repo_candidates(command, cwd):
        try:
            if not Path(repo).is_dir():
                continue
            # --no-renames: without it, git prints only the post-image path
            # for a detected rename (e.g. `git mv real/code.py .claude/plans/x.md`
            # shows as one line, `.claude/plans/x.md`), which would let renamed
            # code slip through the C-2 exemption undetected (FR-22).
            proc = subprocess.run(
                ["git", "diff", "--cached", "--name-only", "--no-renames"],
                cwd=str(repo), capture_output=True, text=True, timeout=10,
            )
            if proc.returncode == 0:
                return [line.strip() for line in proc.stdout.splitlines() if line.strip()]
        except (OSError, subprocess.SubprocessError, ValueError):
            continue
    return []


def commit_uses_dash_a(command: str) -> bool:
    """git commit -a / -am / --all stages every dirty tracked file at commit
    time, after the index was already inspected - an unrelated dirty code file
    would ship silently through the C-2 exemption. Chosen fix: refuse the
    exemption outright for -a/-am/--all rather than diff against `git diff
    HEAD --name-only`, because that HEAD-diff already includes everything the
    plain index check does PLUS every unstaged tracked change, i.e. it is just
    a more expensive way to reach "not all C-2" - refusing directly is the
    same outcome with less surface. Tokenized via git_invocations() so a
    flag-looking substring inside a quoted commit message isn't mistaken for a
    real flag, and a global option can't hide the subcommand.

    KNOWN LIMITATION - this check is textual and NOT total. It only sees flags
    present in the command itself. An `-a` that arrives through git config or an
    alias (`git -c alias.ci='!git commit -a' ci`, or an `[alias]` entry in
    .gitconfig) is invisible here, so such a commit could still be granted the
    C-2 exemption. Resolving aliases would mean shelling out to `git config` per
    repo on every hook call; the trade was judged not worth it. Do not assume
    this function catches every `-a` commit."""
    for sub, args in git_invocations(command):
        if sub == GIT_UNKNOWN:
            return True  # unparseable git text - refuse the exemption
        if sub != "commit":
            continue
        for tok in args:
            if tok == "--":
                break
            if tok == "--all":
                return True
            if tok.startswith("-") and not tok.startswith("--") and "a" in tok[1:]:
                return True
    return False


def planning_only_commit(command: str, cwd: str) -> bool:
    """FR-21/FR-22: the exemption applies only when every staged path matches
    C-2 - all-or-nothing by construction, so one path outside the set
    disqualifies the whole commit. No staged files means nothing to exempt.
    A `-a`/`-am`/`--all` commit never qualifies (see commit_uses_dash_a)."""
    if commit_uses_dash_a(command):
        return False
    files = staged_files(command, cwd)
    return bool(files) and all(matches_c2(f) for f in files)


def check_destructive_and_repl(command: str, low: str) -> int:
    """A + B + G, all data-driven from pipeline.json 'gates' so no project/stack
    scope leaks into the code."""
    cfg = gates_cfg()

    if cfg.get("forbid_dev_null") and "/dev/null" in command:  # B
        return deny("Unix redirect to /dev/null is forbidden in this environment - it "
                    "creates a literal `nul` file. Drop the redirect or use `>NUL` / `2>NUL`.")

    allow_if = [str(s).lower() for s in cfg.get("destructive_allow_if", [])]  # A
    for pat in cfg.get("destructive_command_patterns", []):
        try:
            if re.search(pat, command, re.IGNORECASE):
                if any(a in low for a in allow_if):
                    return allow()
                return deny(f"Destructive command blocked by project policy (matched '{pat}'): "
                            f"it can irreversibly wipe data. Use the safe, additive alternative "
                            f"for this stack. See .claude project rules.")
        except re.error:
            continue

    kw = str(cfg.get("repl_write_keyword", "")).lower()  # G
    if kw and kw in low:
        for pat in cfg.get("repl_write_patterns", []):
            try:
                if re.search(pat, command, re.IGNORECASE):
                    return deny("Write operation inside the live REPL hits the real dev "
                                "database and persists junk. Use a rolled-back test or "
                                "read-only queries instead. See .claude testing rules.")
            except re.error:
                continue
    return allow()


def check_commit_attribution(command: str) -> int:
    """D: no AI-authorship trailer in commit messages."""
    if not git_invokes(command, "commit"):
        return allow()
    if AI_ATTRIB_RE.search(command):
        return deny("Commit message carries an AI-authorship trailer (Co-Authored-By / "
                    "Generated by / AI-assisted). Remove it - no AI attribution in commits, ever.")
    return allow()


def has_forbidden_dash(text: str) -> bool:
    return any(d in text for d in EM_EN_DASH)


def under_home_claude(file_path: str) -> bool:
    """H: writes under the runtime home ~/.claude/ (never the project's own
    .claude/) store project data outside the repo - forbidden. Exception:
    ~/.claude/plans/ is the harness's own plan-mode scratch area (Claude Code
    forces the plan file there); denying it bricks plan mode, and the final
    plan is copied into <project>/.claude/plans/ anyway."""
    try:
        p = Path(file_path).resolve()
        home_claude = (Path.home() / ".claude").resolve()
        if p == home_claude or home_claude in p.parents:
            if (home_claude / "plans") in p.parents:
                return False  # harness plan-mode scratch file - allowed
            # allow if it is actually the project's own .claude (repo under home)
            root_claude = (state.ROOT / ".claude").resolve()
            return not (p == root_claude or root_claude in p.parents)
        return False
    except (OSError, ValueError):
        return False


def active_review_run(conn) -> dict | None:
    """The 'review' stage is read-only: the reviewer analyzes the tree, so a code
    edit underneath it would invalidate the findings it is producing."""
    for r in state.all_runs(conn):
        if r["stage"] == "review" and r["stage_status"] != state.ST_BLOCKED:
            return r
    return None


def is_bookkeeping(path: str) -> bool:
    p = path.replace("\\", "/").lower()
    return "/.claude/" in p or "/docs/" in p or p.startswith((".claude/", "docs/"))


def handoff_freeze_task() -> str:
    """Hard edit gate (config flag handoff.hard_edit_gate): while a completed
    task lacks its handoff doc AND no task is mid-stage, code edits are frozen -
    the debt must be paid first. A task already in an editing stage keeps
    working (it registered before the debt appeared). Lazy import + fail-open:
    '' means no freeze."""
    try:
        import handoff
        if not handoff.cfg().get("hard_edit_gate"):
            return ""
        conn = state.connect()
        try:
            editing = any(r["stage"] in state.EDITING_STAGES
                          and r["stage_status"] != state.ST_BLOCKED
                          for r in state.all_runs(conn))
        finally:
            conn.close()
        if editing:
            return ""
        debt = handoff.uncovered_done_tasks()
        return debt[0]["task"] if debt else ""
    except Exception:
        return ""


def handle_bash(command: str, cwd: str = "", orch: bool = False) -> int:
    low = " ".join(command.lower().split())

    # Parse failure gates, but it must say WHY: this used to fall through to the
    # commit/push block and deny an unparseable heredoc with "Commit for task-XXXX
    # is not approved yet", which names the wrong cause entirely.
    if git_unparseable(command):
        return deny(UNPARSEABLE_GIT_MSG)

    for check in (
        check_branch_creation(command, cwd),      # 4 (naming) + C (base)
        check_destructive_and_repl(command, low),  # A + B + G
        check_commit_attribution(command),         # D
        orch_check_bash(command) if orch else allow(),  # orchestrator profile
    ):
        if check != 0:
            return check

    is_commit = git_invokes(command, "commit")
    is_push = git_invokes(command, "push")
    if not (is_commit or is_push):
        return allow()

    pipeline = state.load_pipeline()
    main_branch = str(pipeline.get("main_branch", "main"))
    if main_branch.startswith("{{"):
        main_branch = "main"

    # FR-1: checked before current_branch() - a repo with no commits has an
    # unborn HEAD, which makes `git rev-parse --abbrev-ref HEAD` fail there and
    # would otherwise fall through repo_candidates() to an unrelated repo.
    if is_commit and repo_bootstrap(command, cwd, main_branch):
        return allow()

    branch = current_branch(command, cwd)

    if is_push:
        verdict = check_push_target(command, branch)
        if verdict != 0:
            return verdict

    task = task_from_branch(branch)
    if not task:
        if is_commit:
            if planning_only_commit(command, cwd):  # FR-21, FR-22
                return allow()
            return deny("Not on a feature branch (no task-XXXX). Create the task branch first "
                        "per .claude/rules/git-workflow.md.")
        return allow()

    conn = state.connect()
    run = state.get_run(conn, task)
    conn.close()
    if run is None:
        return allow()  # task not under pipeline control - don't interfere

    if is_commit and not run["commit_approved"]:
        return deny(f"Commit for {task} is not approved yet. Surface the diff and wait for CEO "
                    f"approval, then: python .claude/tools/pipeline/approve.py --task {task} --gate commit.")
    if is_push and not run["push_approved"]:
        return deny(f"Push for {task} is not approved yet. Wait for CEO approval, then: "
                    f"python .claude/tools/pipeline/approve.py --task {task} --gate push.")
    return allow()


def handle_edit(file_path: str, content: str = "", orch: bool = False) -> int:
    if not file_path:
        return allow()

    if under_home_claude(file_path):  # H
        return deny("Project files must not be written under the runtime home ~/.claude/. "
                    "Keep everything inside the project (its own .claude/, docs/, src, ...).")

    if content and has_forbidden_dash(content):  # F
        return deny("Content contains an em dash or en dash (U+2014 / U+2013). Use a plain "
                    "hyphen '-' everywhere - code, comments, docs, strings. (global rule)")

    if orch:
        code = orch_check_edit(file_path)
        if code != 0:
            return code

    if is_bookkeeping(file_path):
        return allow()
    conn = state.connect()
    review = active_review_run(conn)
    conn.close()
    if review:
        return deny(f"{review['task']} is in the read-only '{review['stage']}' stage - code edits "
                    f"are blocked. To change code, send it back: python "
                    f".claude/tools/pipeline/approve.py --task {review['task']} --reject")
    frozen = handoff_freeze_task()
    if frozen:
        return deny(f"Handoff debt: completed task {frozen} has no valid handoff doc - code edits "
                    f"are frozen (handoff.hard_edit_gate) until the next task's assignee writes it. "
                    f"Scaffold: python .claude/tools/pipeline/handoff.py --for {frozen}, then fill "
                    f".claude/tasks/handoffs/{frozen}.md. Check: handoff.py --check.")
    return allow()


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (ValueError, OSError):
        return allow()
    try:
        tool = payload.get("tool_name", "")
        ti = payload.get("tool_input", {}) or {}
        # Subagent detection: settings-level hooks also fire inside subagents,
        # but the orchestrator profile must only bind the MAIN thread (subagents
        # carry their own frontmatter hooks -> agent_gate.py). Two signals:
        #   1. explicit agent identity keys in the payload (newer harnesses);
        #   2. the transcript path - subagent transcripts live under a
        #      .../subagents/ directory as agent-<id>.jsonl.
        is_subagent = any(str(payload.get(k) or "").strip()
                          for k in ("agent_type", "subagent_type", "agent_name", "agent_id"))
        tp = str(payload.get("transcript_path") or "").replace("\\", "/").lower()
        if "/subagents/" in tp or tp.rsplit("/", 1)[-1].startswith("agent-"):
            is_subagent = True
        orch = not is_subagent
        if tool == "Bash":
            return handle_bash(str(ti.get("command", "")), str(payload.get("cwd", "")), orch=orch)
        if tool in ("Edit", "Write"):
            content = str(ti.get("new_string", "") or ti.get("content", ""))
            return handle_edit(str(ti.get("file_path", "")), content, orch=orch)
        return allow()
    except Exception:
        return allow()


if __name__ == "__main__":
    raise SystemExit(main())
